ComicBookLibraryManagerWebApp/Controllers/ComicBookArtistsController.cs
using ComicBookLibraryManagerWebApp.ViewModels;
using ComicBookShared.Data;
using ComicBookShared.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ComicBookLibraryManagerWebApp.Controllers
{
    /// <summary>
    /// Controller for adding/deleting comic book artists.
    /// </summary>
    public class ComicBookArtistsController : BaseController
    {
        private ComicBookArtistRepository _comicBookArtistRepository = null;
        private ComicBookRepository _comicBookRepository = null;
        private ArtistRepository _artistRepository = null;

        public ComicBookArtistsController()
        {
            _comicBookArtistRepository = new ComicBookArtistRepository(Context);
            _comicBookRepository = new ComicBookRepository(Context);
            _artistRepository = new ArtistRepository(Context);
        }


        public ActionResult Add(int comicBookId)
        {
            // TODO Get the comic book.
            // Include the "Series" navigation property.
            var comicBook = _comicBookRepository.Get(comicBookId);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBookArtistsAddViewModel()
            {
                ComicBook = comicBook
            };

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init(Repository, _artistRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ComicBookArtistsAddViewModel viewModel)
        {
            ValidateComicBookArtist(viewModel);

            if (ModelState.IsValid)
            {
                var comicBookArtist = new ComicBookArtist()
                {
                    ComicBookId = viewModel.ComicBookId,
                    ArtistId = viewModel.ArtistId,
                    RoleId = viewModel.RoleId
                };
                _comicBookArtistRepository.Add(comicBookArtist);

                TempData["Message"] = "Your artist was successfully added!";

                return RedirectToAction("Detail", "ComicBooks", new { id = viewModel.ComicBookId });
            }

            viewModel.ComicBook = _comicBookRepository.Get(viewModel.ComicBookId);
            viewModel.Init(Repository, _artistRepository);

            return View(viewModel);
        }

        public ActionResult Delete(int comicBookId, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBookArtist = _comicBookArtistRepository.Get((int)id);

            if (comicBookArtist == null)
            {
                return HttpNotFound();
            }

            return View(comicBookArtist);
        }

        [HttpPost]
        public ActionResult Delete(int comicBookId, int id)
        {
            // TODO Delete the comic book artist.
            var comicBook = new ComicBook() { Id = id };

            _comicBookArtistRepository.Delete(id);


            //bool saveFailed;
            //do
            //{
            //    saveFailed = false;

            //    try
            //    {
            //        Context.SaveChanges();
            //    }
            //    catch (DbUpdateConcurrencyException ex)
            //    {
            //        saveFailed = true;

            //        // Update the values of the entity that failed to save from the store
            //        ex.Entries.Single().Reload();
            //    }

            //} while (saveFailed);




            TempData["Message"] = "Your artist was successfully deleted!";

            return RedirectToAction("Detail", "ComicBooks", new { id = comicBookId });
        }

        /// <summary>
        /// Validates a comic book artist on the server
        /// before adding a new record.
        /// </summary>
        /// <param name="viewModel">The view model containing the values to validate.</param>
        private void ValidateComicBookArtist(ComicBookArtistsAddViewModel viewModel)
        {
            // If there aren't any "ArtistId" and "RoleId" field validation errors...
            if (_comicBookRepository.ComicBookHasArtistRoleCombination(
                    viewModel.ComicBookId, viewModel.ArtistId, viewModel.RoleId))
            {
                // Then make sure that this artist and role combination 
                // doesn't already exist for this comic book.
                // TODO Call method to check if this artist and role combination
                // already exists for this comic book.
                {
                    ModelState.AddModelError("ArtistId",
                        "This artist and role combination already exists for this comic book.");
                }
            }
        }
    }
}

ComicBookLibraryManagerWebApp/Controllers/ComicBooksController.cs
using ComicBookShared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ComicBookLibraryManagerWebApp.ViewModels;
using System.Net;
using System.Data.Entity.Infrastructure;
using ComicBookShared.Data;

namespace ComicBookLibraryManagerWebApp.Controllers
{
    /// <summary>
    /// Controller for the "Comic Books" section of the website.
    /// </summary>
    public class ComicBooksController : BaseController
    {
        private ComicBookRepository _comicBookRepository = null;
        private SeriesRepository _seriesRepository = null;
        private ArtistRepository _artistRepository = null;

        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository(Context);
            _seriesRepository = new SeriesRepository(Context);
            _artistRepository = new ArtistRepository(Context);
        }


        public ActionResult Index()
        {
            var comicBooks = _comicBookRepository.GetList();

            return View(comicBooks);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBook = _comicBookRepository.Get((int) id);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            // Sort the artists.
            comicBook.Artists = comicBook.Artists.OrderBy(a => a.Role.Name).ToList();

            return View(comicBook);
        }

        public ActionResult Add()
        {
            var viewModel = new ComicBooksAddViewModel();

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ComicBooksAddViewModel viewModel)
        {
            ValidateComicBook(viewModel.ComicBook);

            if (ModelState.IsValid)
            {
                var comicBook = viewModel.ComicBook;
                comicBook.AddArtist(viewModel.ArtistId, viewModel.RoleId);

                _comicBookRepository.Add(comicBook);


                TempData["Message"] = "Your comic book was successfully added!";

                return RedirectToAction("Detail", new { id = comicBook.Id });
            }

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBook = _comicBookRepository.Get((int)id,
                includeRelatedEntities: false);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBooksEditViewModel()
            {
                ComicBook = comicBook
            };
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ComicBooksEditViewModel viewModel)
        {
            ValidateComicBook(viewModel.ComicBook);

            if (ModelState.IsValid)
            {
                var comicBook = viewModel.ComicBook;
                try
                {
                    _comicBookRepository.Update(comicBook);

                    TempData["Message"] = "Your comic book was successfully updated!";

                    return RedirectToAction("Detail", new { id = comicBook.Id });
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    string message = null;

                    var entityPropertyValues = ex.Entries.Single().GetDatabaseValues();

                    if (entityPropertyValues == null)
                    {
                        message = "The comic book being updated has been deleted by another user. Click the 'Cancel' button to return to the list page.";

                        viewModel.ComicBookHasBeenDeleted = true;
                    }
                    else
                    {
                        message = "The comic book being updated has already been upudated by another user. If you would like to save your changes ther click the 'save' button again. Otherwise click the 'Cancel' button to discard your changes";

                        comicBook.RowVersion = ((ComicBook)entityPropertyValues.ToObject()).RowVersion;
                    }

                    ModelState.AddModelError(string.Empty, message);
                } 
            }
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBook = _comicBookRepository.Get((int)id);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBooksDeleteViewModel()
            {
                ComicBook = comicBook
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Delete(ComicBooksDeleteViewModel viewModel)
        {
            try
            {
                _comicBookRepository.Delete(viewModel.ComicBook.Id, viewModel.ComicBook.RowVersion);

                TempData["Message"] = "Your comic book was successfully deleted!";

                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                string message = null;

                var entityPropertyValues = ex.Entries.Single().GetDatabaseValues();

                if (entityPropertyValues == null)
                {
                    message = "The comic book being deleted has been deleted by another user. Click the 'Cancel' button to return to the list page.";

                    viewModel.ComicBookHasBeenDeleted = true;
                }
                else
                {
                    message = "The comic book being deleted has already been updated by another user. If you would like to delete the comic book then click the 'delete' button again. Otherwise click the 'Cancel' button to return to the detail page.";

                    viewModel.ComicBook.RowVersion = ((ComicBook)entityPropertyValues.ToObject()).RowVersion;
                }

                ModelState.AddModelError(string.Empty, message);

                return View(viewModel);
            }    
        }

        /// <summary>
        /// Validates a comic book on the server
        /// before adding a new record or updating an existing record.
        /// </summary>
        /// <param name="comicBook">The comic book to validate.</param>
        private void ValidateComicBook(ComicBook comicBook)
        {
           // If there aren't any "SeriesId" and "IssueNumber" field validation errors...
            if (ModelState.IsValidField("ComicBook.SeriesId") &&
                ModelState.IsValidField("ComicBook.IssueNumber"))
            {
                // Then make sure that the provided issue number is unique for the provided series.
               
                if (_comicBookRepository.ComicBookSeriesHasIssueNuumber(
                        comicBook.Id, comicBook.SeriesId, comicBook.IssueNumber))
                {
                    ModelState.AddModelError("ComicBook.IssueNumber",
                        "The provided Issue Number has already been entered for the selected Series.");
                }
            }
        }
    }
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Add.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksAddViewModel

@{
    ViewBag.Title = "Add Comic Book";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-danger" })

    <h3>Main Information</h3>

    @Html.Partial("_ComicBookForm")

    <h3>First Artist</h3>

    <p>Select an artist and role to add to this comic book. 
        Additional artists can be added once the comic book has been saved.</p>

    <div class="row">

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(m => m.ArtistId, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.ArtistId,
                    Model.ArtistSelectListItems, "", new { @class = "form-control" })
            </div>

        </div>

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(m => m.RoleId, new { @class = "control-label" })
                @Html.DropDownListFor(m => m.RoleId,
                    Model.RoleSelectListItems, "", new { @class = "form-control" })
            </div>

        </div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="pad-top">
                <button type="submit" class="btn btn-success btn-lg margin-right">
                    <span class="glyphicon glyphicon-save"></span> Save
                </button>
                <a href="@Url.Action("Index")" class="btn btn-warning btn-lg">
                    <span class="glyphicon glyphicon-remove"></span> Cancel
                </a>
            </div>
        </div>
    </div>
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Delete.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksDeleteViewModel

@{
    ViewBag.Title = "Delete Comic Book";
}

<h2>@ViewBag.Title</h2>

<div class="alert alert-warning">
    Are you sure you want to delete the comic book @Model.ComicBook.DisplayText?
</div>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-danger" })

    @Html.HiddenFor(m => m.ComicBook.RowVersion)
    @Html.HiddenFor(m => m.ComicBook.Series.Title)
    @Html.HiddenFor(m => m.ComicBook.IssueNumber)

    <div class="pad-top">
        <button type="submit" class="btn btn-danger btn-lg margin-right">
            <span class="glyphicon glyphicon-trash"></span> Delete
        </button>
        <a href="@(Model.ComicBookHasBeenDeleted ? Url.Action("Index") : Url.Action("Detail", new { id = Model.Id }))" class="btn btn-warning btn-lg">
            <span class="glyphicon glyphicon-remove"></span> Cancel
        </a>
    </div>
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Detail.cshtml
@model ComicBookShared.Models.ComicBook

@{
    ViewBag.Title = "Comic Book Detail";
}

@Html.Partial("_Message")

<h2>@Model.DisplayText</h2>

<h3>Main Information</h3>

<div class="row">
    <div class="col-md-6">

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.SeriesId)
            </div>
            <div class="col-xs-8 col-sm-8">
                @Model.Series.Title
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.IssueNumber)
            </div>
            <div class="col-xs-8 col-sm-8">
                @Model.IssueNumber
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.PublishedOn)
            </div>
            <div class="col-xs-8 col-sm-8">
                @Model.PublishedOn.ToShortDateString()
            </div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-sm-4">
                @Html.LabelFor(m => m.AverageRating)
            </div>
            <div class="col-xs-8 col-sm-8">
                @(Model.AverageRating != null ? Model.AverageRating.Value.ToString("n1") : "N/A")
            </div>
        </div>

    </div>
    <div class="col-md-6">

        <div>
            @Html.LabelFor(m => m.Description)
        </div>
        <div>
            @(!string.IsNullOrWhiteSpace(Model.Description) ? Model.Description : "N/A")
        </div>

    </div>
</div>

<h3>Artists</h3>

<div class="pull-right">
    <a href="@Url.Action("Add", "ComicBookArtists", new { comicbookid = Model.Id })" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Add Artist
    </a>
</div>

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>Role</th>
            <th>Artist</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var artist in Model.Artists)
        {
            <tr>
                <td>@artist.Role.Name</td>
                <td>@artist.Artist.Name</td>
                <td>
                    <div class="pull-right">
                        <a href="@Url.Action("Delete", "ComicBookArtists", new { comicbookid = Model.Id, id = artist.Id })" class="btn btn-danger btn-xs margin-right">
                            <span class="glyphicon glyphicon-trash"></span><span class="hidden-xs"> Delete</span>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pad-top">
    <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-primary btn-lg margin-right">
        <span class="glyphicon glyphicon-edit"></span> Edit
    </a>
    <a href="@Url.Action("Delete", new { id = Model.Id })" class="btn btn-danger btn-lg margin-right">
        <span class="glyphicon glyphicon-trash"></span> Delete
    </a>
    <a href="@Url.Action("Index")" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-step-backward"></span> Back
    </a>
</div>

ComicBookLibraryManagerWebApp/Views/ComicBooks/Edit.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksEditViewModel

@{
    ViewBag.Title = "Edit Comic Book";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-danger" })

    <h3>Main Information</h3>

    @Html.Partial("_ComicBookForm")

    <div class="row">
        <div class="col-md-12">
            <div class="pad-top">
                <button type="submit" class="btn btn-success btn-lg margin-right">
                    <span class="glyphicon glyphicon-save"></span> Save
                </button>
                <a href="@(Model.ComicBookHasBeenDeleted ? Url.Action("Index") : Url.Action("Detail", new { id = Model.Id }))" class="btn btn-warning btn-lg">
                    <span class="glyphicon glyphicon-remove"></span> Cancel
                </a>
            </div>
        </div>
    </div>
}

ComicBookLibraryManagerWebApp/Views/ComicBooks/Index.cshtml
@model List<ComicBookShared.Models.ComicBook>

@{
    ViewBag.Title = "Comic Books";
}

@Html.Partial("_Message")

<h2>@ViewBag.Title</h2>

<div class="pull-right">
    <a href="@Url.Action("Add")" class="btn btn-primary btn-lg">
        <span class="glyphicon glyphicon-plus"></span> Add Comic Book
    </a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Comic Book</th>
            <th>Published On</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comicBook in Model)
        {
            <tr>
                <td>@comicBook.DisplayText</td>
                <td>@comicBook.PublishedOn.ToString("MM/dd/yyyy")</td>
                <td>
                    <div class="pull-right">
                        <a href="@Url.Action("Detail", new { id = comicBook.Id })" class="btn btn-primary btn-xs margin-right">
                            <span class="glyphicon glyphicon-info-sign"></span><span class="hidden-xs"> Detail</span>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ComicBookLibraryManagerWebApp/Views/ComicBooks/_ComicBookForm.cshtml
@model ComicBookLibraryManagerWebApp.ViewModels.ComicBooksBaseViewModel

<div class="row">

    <div class="col-md-6">

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.SeriesId, new { @class = "control-label" })
            @Html.DropDownListFor(m => m.ComicBook.SeriesId,
            Model.SeriesSelectListItems, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.IssueNumber, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.ComicBook.IssueNumber, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.PublishedOn, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.ComicBook.PublishedOn, "{0:d}", new { @class = "form-control datepicker" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.AverageRating, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.ComicBook.AverageRating, "{0:n1}", new { @class = "form-control" })
        </div>

    </div>

    <div class="col-md-6">

        <div class="form-group">
            @Html.LabelFor(m => m.ComicBook.Description, new { @class = "control-label" })
            @Html.TextAreaFor(m => m.ComicBook.Description, 14, 20, new { @class = "form-control" })
        </div>

    </div>

</div>

@Html.HiddenFor(m => m.ComicBook.RowVersion)