ComicBookLibraryManagerWebApp/Controllers/ComicBooksController.cs
using ComicBookShared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ComicBookLibraryManagerWebApp.ViewModels;
using System.Net;
using System.Data.Entity.Infrastructure;
using ComicBookShared.Data;

namespace ComicBookLibraryManagerWebApp.Controllers
{
    /// <summary>
    /// Controller for the "Comic Books" section of the website.
    /// </summary>
    public class ComicBooksController : BaseController
    {
        private ComicBookRepository _comicBookRepository = null;
        private SeriesRepository _seriesRepository = null;
        private ArtistRepository _artistRepository = null;

        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository(Context);
            _seriesRepository = new SeriesRepository(Context);
            _artistRepository = new ArtistRepository(Context);
        }


        public ActionResult Index()
        {
            var comicBooks = _comicBookRepository.GetList();

            return View(comicBooks);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBook = _comicBookRepository.Get((int) id);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            // Sort the artists.
            comicBook.Artists = comicBook.Artists.OrderBy(a => a.Role.Name).ToList();

            return View(comicBook);
        }

        public ActionResult Add()
        {
            var viewModel = new ComicBooksAddViewModel();

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ComicBooksAddViewModel viewModel)
        {
            ValidateComicBook(viewModel.ComicBook);

            if (ModelState.IsValid)
            {
                var comicBook = viewModel.ComicBook;
                comicBook.AddArtist(viewModel.ArtistId, viewModel.RoleId);

                _comicBookRepository.Add(comicBook);


                TempData["Message"] = "Your comic book was successfully added!";

                return RedirectToAction("Detail", new { id = comicBook.Id });
            }

            // TODO Pass the Context class to the view model "Init" method.
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBook = _comicBookRepository.Get((int)id,
                includeRelatedEntities: false);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBooksEditViewModel()
            {
                ComicBook = comicBook
            };
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ComicBooksEditViewModel viewModel)
        {
            ValidateComicBook(viewModel.ComicBook);

            if (ModelState.IsValid)
            {
                var comicBook = viewModel.ComicBook;
                try
                {
                    _comicBookRepository.Update(comicBook);

                    TempData["Message"] = "Your comic book was successfully updated!";

                    return RedirectToAction("Detail", new { id = comicBook.Id });
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    string message = null;

                    var entityPropertyValues = ex.Entries.Single().GetDatabaseValues();

                    if (entityPropertyValues == null)
                    {
                        message = "The comic book being updated has been deleted by another user. Click the 'Cancel' button to return to the list page.";

                        viewModel.ComicBookHasBeenDeleted = true;
                    }
                    else
                    {
                        message = "The comic book being updated has already been upudated by another user. If you would like to save your changes ther click the 'save' button again. Otherwise click the 'Cancel' button to discard your changes";

                        comicBook.RowVersion = ((ComicBook)entityPropertyValues.ToObject()).RowVersion;
                    }

                    ModelState.AddModelError(string.Empty, message);
                } 
            }
            viewModel.Init(Repository, _seriesRepository, _artistRepository);

            return View(viewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comicBook = _comicBookRepository.Get((int)id);

            if (comicBook == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ComicBooksDeleteViewModel()
            {
                ComicBook = comicBook
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Delete(ComicBooksDeleteViewModel viewModel)
        {
            try
            {
                _comicBookRepository.Delete(viewModel.ComicBook.Id, viewModel.ComicBook.RowVersion);

                TempData["Message"] = "Your comic book was successfully deleted!";

                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                string message = null;

                var entityPropertyValues = ex.Entries.Single().GetDatabaseValues();

                if (entityPropertyValues == null)
                {
                    message = "The comic book being deleted has been deleted by another user. Click the 'Cancel' button to return to the list page.";

                    viewModel.ComicBookHasBeenDeleted = true;
                }
                else
                {
                    message = "The comic book being deleted has already been updated by another user. If you would like to delete the comic book then click the 'delete' button again. Otherwise click the 'Cancel' button to return to the detail page.";

                    viewModel.ComicBook.RowVersion = ((ComicBook)entityPropertyValues.ToObject()).RowVersion;
                }

                ModelState.AddModelError(string.Empty, message);

                return View(viewModel);
            }    
        }

        /// <summary>
        /// Validates a comic book on the server
        /// before adding a new record or updating an existing record.
        /// </summary>
        /// <param name="comicBook">The comic book to validate.</param>
        private void ValidateComicBook(ComicBook comicBook)
        {
           // If there aren't any "SeriesId" and "IssueNumber" field validation errors...
            if (ModelState.IsValidField("ComicBook.SeriesId") &&
                ModelState.IsValidField("ComicBook.IssueNumber"))
            {
                // Then make sure that the provided issue number is unique for the provided series.
               
                if (_comicBookRepository.ComicBookSeriesHasIssueNuumber(
                        comicBook.Id, comicBook.SeriesId, comicBook.IssueNumber))
                {
                    ModelState.AddModelError("ComicBook.IssueNumber",
                        "The provided Issue Number has already been entered for the selected Series.");
                }
            }
        }
    }
}

ComicBookLibraryManagerWebApp/Views/Shared/_Layout.cshtml
@{ 
    var applicationName = "Comic Book Library Manager";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @applicationName</title>
    <link href="~/Content/bootstrap-lumen.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(applicationName, "Index", "ComicBooks", new { }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="@(ViewContext.RouteData.Values["Controller"].ToString() == "ComicBooks" ? "active" : "")">@Html.ActionLink("Comic Books", "Index", "ComicBooks")</li>
                    <li class="@(ViewContext.RouteData.Values["Controller"].ToString() == "Series" ? "active" : "")">@Html.ActionLink("Series", "Index", "Series")</li>
                    <li class="@(ViewContext.RouteData.Values["Controller"].ToString() == "Artists" ? "active" : "")">@Html.ActionLink("Artists", "Index", "Artists")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @applicationName</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script>
        $('input.datepicker').datepicker({
            format: 'm/d/yyyy'
        });
    </script>
</body>
</html>

ComicBookLibraryManagerWebApp/Views/Shared/_Message.cshtml
@if (TempData["Message"] != null)
{
    <p>&nbsp;</p>

    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["Message"]
    </div>
}